### PR TITLE
fixed race in Pack() on default options initialization.

### PR DESCRIPTION
**Pull request by serejkus**
Default Options used in Pack() is a global object with zero-initialized
fields. Validate() changes PtrSize field value on the first call
from zero to 32. It is a data race if multiple goroutines call Pack().

This commit fixes this issue and adds a tests its correctnes. Important
note about test is that it should be in a separate package because
it needs to be run exclusively so that it is guaranteed that it is run
first to catch this race condition.

### CODE REVIEW

**Comment by lunixbochs** [comment]
I don’t believe there’s actually a data race here on any platforms Go supports, because all racing threads should write, then read, the same value regardless of cache and instruction ordering. So this patch just fixes “the data race detector incorrectly identifies multiple threads making the same constant assignment as a race”.

Instead of referencing the default value in multiple places, we can just put an init func right below defaultOptions that calls Validate() on it at import time

**Comment by serejkus** [comment]
“the data race detector incorrectly identifies multiple threads making the same constant assignment as a race”. Exactly. Binaries with race detector enabled report this as an issue sometimes.

**Comment by serejkus** [comment]
Do you have any clues on what's happening in Go 1.2 build in travis?

**Comment by lunixbochs** [comment]
It says “I don't have any idea what to do with '1.2'.” We can just drop the Go 1.2 test, probably add a Go 1.13 test.

**Comment by serejkus** [comment]
Looks like all checks have passed. Any plans on merge?

**Pull request merged**
