### PR TITLE
Add native tag to use host byte order

### LINKED ISSUE #68: default byte order?
what is the default byte order used if none is specified in the field tag? is there a way to inherit the default byte order of the system?

### PR DESCRIPTION
**Pull request by tmm1**
fixes #68

### CODE REVIEW

**Comment by lunixbochs** [comment]
Adding a dependency on `unsafe` means we can't run in sandboxed Go environments. I'd like to see if we can detect native byte order another way.

**Comment by tmm1** [comment]
> call PackWithOptions w/ the byte order option

Aha, this is what I was missing! Thank you.

**Comment by tmm1** [comment]
Looks like there's `PackWithOrder` too. I've opened #72 so its easier for others to discover the APIs available.

**Comment by lunixbochs** [comment]
I wanted to deprecate PackWithOrder, it's very similar to use PackWithOptions which also provides other options

**Pull request closed without merging**
